// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Demo struct { // demo (../../../../../:0:0)
	query *querybuilder.Selection

	hello *Void
	id    *ID
}

func (r *Demo) WithGraphQLQuery(q *querybuilder.Selection) *Demo {
	return &Demo{
		query: q,
	}
}

// Compile the hello program and return the binary.
func (r *Demo) Build() *File {
	q := r.query.Select("build")

	return &File{
		query: q,
	}
}

// Compile the hello program and run it.
func (r *Demo) Hello(ctx context.Context) error {
	if r.hello != nil {
		return nil
	}
	q := r.query.Select("hello")

	return q.Execute(ctx)
}

// A unique identifier for this Demo.
func (r *Demo) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Demo) XXX_GraphQLType() string {
	return "Demo"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Demo) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Demo) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Demo) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Demo) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Demo{query: selectNode(dag.query, id, "Demo")}
	return nil
}

func (r *Query) Demo(ws *Workspace) *Demo { // demo (../../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("demo")
	q = q.Arg("ws", ws)

	return &Demo{
		query: q,
	}
}
